#    ______ _           _ _____            __ _
#   |  ___| |         (_)  __ \          / _| |
#   | |_  | | _____  ___| /  \/_ __ __ _| |_| |_
#   |  _| | |/ _ \ \/ / | |   | '__/ _` |  _| __|
#   | |   | |  __/>  <| | \__/\ | | (_| | | | |_
#   \_|   |_|\___/_/\_\_|\____/_|  \__,_|_|  \__|

# Made by OlliesWorld

# Join Leave messages
leave-message: '&eFlexi&6Craft &7>> %player% has &cleft &7the game!'
join-message: '&eFlexi&6Craft &7>> %player% has &ajoined &7the game!'
first-time-join-message: '&e&lFlexi&6&lCraft &7&l>> %player% has &a&ljoined &7&lfor the first time!'